# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.21
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Mod
mod_id=sereneregions
mod_name=Serene Regions
mod_license=MIT
mod_version=1.0-1.20.1
mod_group_id=net.demolutio.sereneregions
mod_authors=demolutio, luisaava
mod_description=This mod adds compatibility between Serene Seasons and Regions Unexplored!